### ISSUE TITLE
Question about config.js

### ISSUE THREAD

**Issue by Tiritibambix** [nicholaswilde/docker-cryptpad#37]
Hello, that's me again :D 

I'm having trouble setting up my config.js. Specially in order to get access to the admin panel.
I have syntaxe problems all over the place and the the config.example.js is full of commented lines and I mess things up.

Can somebody share here his config.js so I can get inspired from it please ?

**Comment by nicholaswilde** [comment]
Have you tried looking at the example config on the main repo? https://github.com/xwiki-labs/cryptpad/blob/c774a5d06e755d1113ff2ee70cc4b276fc91dc9c/config/config.example.js

**Comment by Tiritibambix** [comment]
Hello,!
Yes, I did : "the the config.example.js is full of commented lines and I mess things up." :D

I just need to understand the proper syntaxe, because when I uncomment a line I need or edit something, I mess things up. A clean example would be sooo helpful

**Comment by Tiritibambix** [comment]
ok so, if copy and rename config.example.js into config.js and change _nothing_ apart from the user key, I get  a "502 Bad Gateway"

here's how my config looks like in the admin part :

```
[...]
     *  key, which can be found on the settings page for registered users.
     *  Entries should be strings separated by a comma.
     */
/*
    adminKeys: [
        //"[cryptpad-user1@my.awesome.website/YZgXQxKR0Rcb6r6CmxHPdAGLVludrAF2lEnkbx1vVOo=]",
    ],
*/

    /* =====================
     *        STORAGE
     * ===================== */

    /*  Pads that are not 'pinned' by any registered user can be
[...]
```
Of course I replaced this example by my own user key

**Comment by Tiritibambix** [comment]
For anyone interested, here's how I managed this

https://www.reddit.com/r/selfhosted/comments/ohntyu/selfhosting_cryptpad_with_docker_and_configjs/

**Comment by nicholaswilde** [comment]
Thanks for posting your solution! 🙏
