### ISSUE TITLE
Include installMethod property in server telemetry

### ISSUE THREAD

**Issue by ansuz** [nicholaswilde/docker-cryptpad#39]
Hi,

I just made the same request on the [YunoHost repository](https://github.com/YunoHost-Apps/cryptpad_ynh/issues/102), so I'll just link that and skip the detailed writeup.

> Please set the `installMethod` property of the nodejs server's config file to a custom string indicating that the server was installed via ~~YunoHost~~. `nicholaswilde/docker-cryptpad`

[This PR against xwiki-labs/cryptpad-docker](https://github.com/xwiki-labs/cryptpad-docker/pull/26) should be sufficient as an example.

**Comment by nicholaswilde** [comment]
Thanks for submitting this. I'll look into it for the next release of the image, 4.10.0, and I'll let you know if I have any questions.

**Comment by ansuz** [comment]
Thanks!
