### ISSUE TITLE
v5.0 support

### ISSUE THREAD

**Issue by austinhuang0131** [nicholaswilde/docker-cryptpad#79]
https://github.com/xwiki-labs/cryptpad/releases/tag/5.0.0

**Comment by nicholaswilde** [comment]
Yeah, I've been meaning to get to this. I haven't had a chance to  look into it. Do you happen to know if there's anything drastic that has changed since the 5.0.0 release that I need to look out for?

**Comment by austinhuang0131** [comment]
Doesn't look like it but I asked in the Matrix room anyway.

**Comment by nicholaswilde** [comment]
I appreciate it.

**Comment by nicholaswilde** [comment]
[Released](https://github.com/nicholaswilde/docker-cryptpad/pkgs/container/cryptpad/28606445?tag=5.0.0-ls22)
